TYPE=VIEW
query=select `db_rental_mobil`.`transaksisewa`.`NoTransaksi` AS `NoTransaksi`,`db_rental_mobil`.`transaksisewa`.`NIK` AS `NIK`,`db_rental_mobil`.`transaksisewa`.`NoPlat` AS `NoPlat`,`db_rental_mobil`.`transaksisewa`.`IDSopir` AS `IDSopir`,`db_rental_mobil`.`transaksisewa`.`NoKTP` AS `NoKTP` from `db_rental_mobil`.`transaksisewa`
md5=e9d7bc9b8ba53bea3983427162064bd3
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2017-01-26 00:21:59
create-version=2
source=SELECT NoTransaksi,NIK,NoPlat,IDSopir,NoKTP FROM transaksisewa
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `db_rental_mobil`.`transaksisewa`.`NoTransaksi` AS `NoTransaksi`,`db_rental_mobil`.`transaksisewa`.`NIK` AS `NIK`,`db_rental_mobil`.`transaksisewa`.`NoPlat` AS `NoPlat`,`db_rental_mobil`.`transaksisewa`.`IDSopir` AS `IDSopir`,`db_rental_mobil`.`transaksisewa`.`NoKTP` AS `NoKTP` from `db_rental_mobil`.`transaksisewa`
mariadb-version=100119
