TYPE=VIEW
query=select `db_rental_mobil`.`karyawan`.`NIK` AS `NIK`,`db_rental_mobil`.`karyawan`.`NmKaryawan` AS `NmKaryawan`,`db_rental_mobil`.`karyawan`.`AlmtKaryawan` AS `AlmtKaryawan`,`db_rental_mobil`.`karyawan`.`TelpKaryawan` AS `TelpKaryawan` from `db_rental_mobil`.`karyawan`
md5=c094d1af32ebb6eb13fc7c7284603735
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2017-01-25 03:49:19
create-version=2
source=SELECT * FROM karyawan
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `db_rental_mobil`.`karyawan`.`NIK` AS `NIK`,`db_rental_mobil`.`karyawan`.`NmKaryawan` AS `NmKaryawan`,`db_rental_mobil`.`karyawan`.`AlmtKaryawan` AS `AlmtKaryawan`,`db_rental_mobil`.`karyawan`.`TelpKaryawan` AS `TelpKaryawan` from `db_rental_mobil`.`karyawan`
mariadb-version=100119
