TYPE=VIEW
query=select `db_rental_mobil`.`sopir`.`IDSopir` AS `IDSopir`,`db_rental_mobil`.`sopir`.`NmSopir` AS `NmSopir`,`db_rental_mobil`.`sopir`.`AlmSopir` AS `AlmSopir`,`db_rental_mobil`.`sopir`.`TelpSopir` AS `TelpSopir`,`db_rental_mobil`.`sopir`.`NoSIM` AS `NoSIM`,`db_rental_mobil`.`sopir`.`TarifPerJam` AS `TarifPerJam` from `db_rental_mobil`.`sopir`
md5=90741a05ea0a13c494405c481721ed22
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2017-01-23 06:53:44
create-version=2
source=SELECT * FROM sopir
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `db_rental_mobil`.`sopir`.`IDSopir` AS `IDSopir`,`db_rental_mobil`.`sopir`.`NmSopir` AS `NmSopir`,`db_rental_mobil`.`sopir`.`AlmSopir` AS `AlmSopir`,`db_rental_mobil`.`sopir`.`TelpSopir` AS `TelpSopir`,`db_rental_mobil`.`sopir`.`NoSIM` AS `NoSIM`,`db_rental_mobil`.`sopir`.`TarifPerJam` AS `TarifPerJam` from `db_rental_mobil`.`sopir`
mariadb-version=100119
