TYPE=VIEW
query=select `db_rental_mobil`.`jenisservice`.`IDJenisService` AS `IDJenisService`,`db_rental_mobil`.`jenisservice`.`NmJenisService` AS `NmJenisService` from `db_rental_mobil`.`jenisservice`
md5=10ac737b75e66bb8fb492a68464a7c43
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2017-02-03 17:19:18
create-version=2
source=SELECT * FROM jenisservice
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `db_rental_mobil`.`jenisservice`.`IDJenisService` AS `IDJenisService`,`db_rental_mobil`.`jenisservice`.`NmJenisService` AS `NmJenisService` from `db_rental_mobil`.`jenisservice`
mariadb-version=100119
