TYPE=VIEW
query=select `db_rental_mobil`.`transaksisewa`.`NoTransaksi` AS `NoTransaksi`,`db_rental_mobil`.`transaksisewa`.`TglPesan` AS `TglPesan`,`db_rental_mobil`.`transaksisewa`.`TglPinjam` AS `TglPinjam`,`db_rental_mobil`.`transaksisewa`.`JamPinjam` AS `JamPinjam`,`db_rental_mobil`.`transaksisewa`.`tglkembalirencana` AS `tglkembalirencana`,`db_rental_mobil`.`transaksisewa`.`TglPinjamRencana` AS `TglPinjamRencana`,`db_rental_mobil`.`transaksisewa`.`JamKembaliRencana` AS `JamKembaliRencana`,`db_rental_mobil`.`transaksisewa`.`TglKembaliRealisasi` AS `TglKembaliRealisasi`,`db_rental_mobil`.`transaksisewa`.`JamKembaliReal` AS `JamKembaliReal`,`db_rental_mobil`.`transaksisewa`.`Denda` AS `Denda`,`db_rental_mobil`.`transaksisewa`.`KiloMeterPinjam` AS `KiloMeterPinjam`,`db_rental_mobil`.`transaksisewa`.`KiloMeterKembali` AS `KiloMeterKembali`,`db_rental_mobil`.`transaksisewa`.`BBMPinjam` AS `BBMPinjam`,`db_rental_mobil`.`transaksisewa`.`BBMKembali` AS `BBMKembali`,`db_rental_mobil`.`transaksisewa`.`KondisiMobilPinjam` AS `KondisiMobilPinjam`,`db_rental_mobil`.`transaksisewa`.`KondisiMobilKembali` AS `KondisiMobilKembali`,`db_rental_mobil`.`transaksisewa`.`Kerusakan` AS `Kerusakan`,`db_rental_mobil`.`transaksisewa`.`BiayaKerusakan` AS `BiayaKerusakan`,`db_rental_mobil`.`transaksisewa`.`BiayaBBM` AS `BiayaBBM`,`db_rental_mobil`.`transaksisewa`.`NIK` AS `NIK`,`db_rental_mobil`.`transaksisewa`.`NoPlat` AS `NoPlat`,`db_rental_mobil`.`transaksisewa`.`IDSopir` AS `IDSopir`,`db_rental_mobil`.`transaksisewa`.`NoKTP` AS `NoKTP` from `db_rental_mobil`.`transaksisewa` where ((`db_rental_mobil`.`transaksisewa`.`TglKembaliRealisasi` = \'0000-00-00\') and (`db_rental_mobil`.`transaksisewa`.`JamKembaliReal` = \'00:00:00\'))
md5=3481d562b8d3064c3a0307f34a6fbe2f
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2017-02-03 03:34:01
create-version=2
source=SELECT * FROM transaksisewa WHERE tglkembalirealisasi = \'0000-00-00\' AND jamkembalireal = \'00:00:00\'
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `db_rental_mobil`.`transaksisewa`.`NoTransaksi` AS `NoTransaksi`,`db_rental_mobil`.`transaksisewa`.`TglPesan` AS `TglPesan`,`db_rental_mobil`.`transaksisewa`.`TglPinjam` AS `TglPinjam`,`db_rental_mobil`.`transaksisewa`.`JamPinjam` AS `JamPinjam`,`db_rental_mobil`.`transaksisewa`.`tglkembalirencana` AS `tglkembalirencana`,`db_rental_mobil`.`transaksisewa`.`TglPinjamRencana` AS `TglPinjamRencana`,`db_rental_mobil`.`transaksisewa`.`JamKembaliRencana` AS `JamKembaliRencana`,`db_rental_mobil`.`transaksisewa`.`TglKembaliRealisasi` AS `TglKembaliRealisasi`,`db_rental_mobil`.`transaksisewa`.`JamKembaliReal` AS `JamKembaliReal`,`db_rental_mobil`.`transaksisewa`.`Denda` AS `Denda`,`db_rental_mobil`.`transaksisewa`.`KiloMeterPinjam` AS `KiloMeterPinjam`,`db_rental_mobil`.`transaksisewa`.`KiloMeterKembali` AS `KiloMeterKembali`,`db_rental_mobil`.`transaksisewa`.`BBMPinjam` AS `BBMPinjam`,`db_rental_mobil`.`transaksisewa`.`BBMKembali` AS `BBMKembali`,`db_rental_mobil`.`transaksisewa`.`KondisiMobilPinjam` AS `KondisiMobilPinjam`,`db_rental_mobil`.`transaksisewa`.`KondisiMobilKembali` AS `KondisiMobilKembali`,`db_rental_mobil`.`transaksisewa`.`Kerusakan` AS `Kerusakan`,`db_rental_mobil`.`transaksisewa`.`BiayaKerusakan` AS `BiayaKerusakan`,`db_rental_mobil`.`transaksisewa`.`BiayaBBM` AS `BiayaBBM`,`db_rental_mobil`.`transaksisewa`.`NIK` AS `NIK`,`db_rental_mobil`.`transaksisewa`.`NoPlat` AS `NoPlat`,`db_rental_mobil`.`transaksisewa`.`IDSopir` AS `IDSopir`,`db_rental_mobil`.`transaksisewa`.`NoKTP` AS `NoKTP` from `db_rental_mobil`.`transaksisewa` where ((`db_rental_mobil`.`transaksisewa`.`TglKembaliRealisasi` = \'0000-00-00\') and (`db_rental_mobil`.`transaksisewa`.`JamKembaliReal` = \'00:00:00\'))
mariadb-version=100119
